# Generated by Django 2.0.1 on 2018-03-23 19:14
# pylint: skip-file
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('segmentation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceSeparator',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('classic', 'Classic')], max_length=10)),
                ('source_separation_status', models.CharField(choices=[('not_started', 'Not started'), ('pending', 'Pending...'), ('failed', 'Failed'), ('done', 'Done')], default='not_started', max_length=15)),
                ('data_path', models.CharField(max_length=500, null=True)),
                ('segmenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_separators', to='segmentation.Segmenter')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='sourceseparator',
            unique_together={('segmenter', 'method')},
        ),
    ]
