# Generated by Django 2.0.1 on 2018-03-25 20:42

import audiofield.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('segmentation', '0002_auto_20180323_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentGrouper',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('classic', 'Classic')], max_length=10)),
                ('segment_grouping_status', models.CharField(choices=[('not_started', 'Not started'), ('pending', 'Pending...'), ('failed', 'Failed'), ('done', 'Done')], default='not_started', max_length=15)),
                ('data_path', models.CharField(max_length=500, null=True)),
                ('segmenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_extractors', to='segmentation.Segmenter')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('source_index', models.PositiveSmallIntegerField()),
                ('segment_group', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=None)),
                ('audio_file', audiofield.fields.AudioField(blank=True, help_text='Allowed type: .wav', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SourceExtractor',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('classic', 'Classic')], max_length=10)),
                ('source_separation_status', models.CharField(choices=[('not_started', 'Not started'), ('pending', 'Pending...'), ('failed', 'Failed'), ('done', 'Done')], default='not_started', max_length=15)),
                ('data_path', models.CharField(max_length=500, null=True)),
                ('segment_grouper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_extractors', to='source_separation.SegmentGrouper')),
            ],
        ),
        migrations.AddField(
            model_name='source',
            name='source_extractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='source_separation.SourceExtractor'),
        ),
        migrations.AlterUniqueTogether(
            name='sourceextractor',
            unique_together={('segment_grouper', 'method')},
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together={('source_index', 'source_extractor')},
        ),
        migrations.AlterUniqueTogether(
            name='segmentgrouper',
            unique_together={('segmenter', 'method')},
        ),
    ]
