# pylint: skip-file
# Generated by Django 2.0.1 on 2018-04-11 20:55

import audiofield.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('segmentation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentGrouper',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('processing_status', models.CharField(choices=[('not_started', 'Not started'), ('pending', 'Pending...'), ('failed', 'Failed'), ('done', 'Done')], default='not_started', max_length=15)),
                ('method', models.CharField(choices=[('classic', 'Classic')], max_length=10)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_groupers', to='segmentation.Segmenter')),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('audio_file', audiofield.fields.AudioField(blank=True, help_text='Allowed type: .wav', max_length=500, upload_to='')),
                ('ind', models.PositiveSmallIntegerField()),
                ('segment_group', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SourceExtractor',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('processing_status', models.CharField(choices=[('not_started', 'Not started'), ('pending', 'Pending...'), ('failed', 'Failed'), ('done', 'Done')], default='not_started', max_length=15)),
                ('method', models.CharField(choices=[('classic', 'Classic')], max_length=10)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_extractors', to='source_separation.SegmentGrouper')),
            ],
        ),
        migrations.AddField(
            model_name='source',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='source_separation.SourceExtractor'),
        ),
        migrations.AlterUniqueTogether(
            name='sourceextractor',
            unique_together={('parent', 'method')},
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together={('ind', 'parent')},
        ),
        migrations.AlterUniqueTogether(
            name='segmentgrouper',
            unique_together={('parent', 'method')},
        ),
    ]
