# Generated by Django 2.0.1 on 2018-04-02 19:37
# pylint: skip-file
import audiofield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source_separation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='audio_file',
            field=audiofield.fields.AudioField(blank=True, help_text='Allowed type: .wav', max_length=500, upload_to=''),
        ),
    ]
