# Generated by Django 2.0.1 on 2018-03-23 19:49
# pylint: skip-file
import audiofield.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('source_separation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('source_index', models.PositiveIntegerField()),
                ('segment_group', models.PositiveIntegerField()),
                ('audio_file', audiofield.fields.AudioField(blank=True, help_text='Allowed type: .wav', upload_to='')),
                ('source_separator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='source_separation.SourceSeparator')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together={('source_index', 'source_separator')},
        ),
    ]
