# pylint:skip-file
#
# # Generated by Django 2.0.1 on 2018-05-27 18:28

import audiofield.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('source_separation', '0002_auto_20180527_1654'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentGroup',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('audio_file', audiofield.fields.AudioField(blank=True, help_text='Allowed type: .wav', max_length=500, upload_to='')),
                ('ind', models.PositiveSmallIntegerField()),
                ('segment_group', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=None)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_groups',
                                             to='source_separation.SegmentGrouper')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='segmentgroup',
            unique_together={('ind', 'parent')},
        ),
    ]
