# Generated by Django 2.0.1 on 2018-04-02 20:34
# pylint: skip-file
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source_separation', '0002_auto_20180402_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='source',
            old_name='source_index',
            new_name='ind',
        ),
        migrations.RenameField(
            model_name='source',
            old_name='source_extractor',
            new_name='parent',
        ),
        migrations.AlterUniqueTogether(
            name='source',
            unique_together={('ind', 'parent')},
        ),
    ]
