# Generated by Django 2.0.1 on 2018-03-23 20:05
# pylint: skip-file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source_separation', '0002_auto_20180323_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='segment_group',
        ),
        migrations.AlterField(
            model_name='source',
            name='source_index',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
