# Generated by Django 2.0.1 on 2018-03-23 20:06
# pylint: skip-file
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source_separation', '0003_auto_20180323_2005'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='segment_group',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=None),
        ),
    ]
