# Generated by Django 2.0.1 on 2018-04-08 11:26

import audiofield.fields
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('source_separation', '0003_auto_20180402_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentGroup',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('ind', models.PositiveIntegerField(verbose_name='Index')),
                ('audio_file', audiofield.fields.AudioField(blank=True, help_text='Allowed type: .wav', max_length=500, upload_to='')),
                ('segment_group', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='segmentgrouper',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_groupers', to='segmentation.Segmenter'),
        ),
        migrations.AlterField(
            model_name='source',
            name='ind',
            field=models.PositiveIntegerField(verbose_name='Index'),
        ),
        migrations.AlterField(
            model_name='source',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output', to='source_separation.SourceExtractor'),
        ),
        migrations.AddField(
            model_name='segmentgroup',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output', to='source_separation.SegmentGrouper'),
        ),
        migrations.AlterUniqueTogether(
            name='segmentgroup',
            unique_together={('ind', 'parent')},
        ),
    ]
