# Generated by Django 2.0.1 on 2018-04-08 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source_separation', '0004_auto_20180408_1126'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='segmentgroup',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='segmentgroup',
            name='parent',
        ),
        migrations.AlterField(
            model_name='source',
            name='ind',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='source',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='source_separation.SourceExtractor'),
        ),
        migrations.DeleteModel(
            name='SegmentGroup',
        ),
    ]
