# Generated by Django 2.0.1 on 2018-02-19 22:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('song', '0007_song_tempo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('index', models.PositiveIntegerField()),
                ('length_in_samples', models.PositiveIntegerField()),
                ('start_position_in_song', models.PositiveIntegerField()),
                ('end_position_in_song', models.PositiveIntegerField()),
                ('audio_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='SegmentList',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segment_list', to='song.Song')),
            ],
        ),
        migrations.AddField(
            model_name='segment',
            name='segment_list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='segmentation.SegmentList'),
        ),
    ]
