# Generated by Django 2.0.1 on 2018-04-02 20:24
# pylint: skip-file
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='segment',
            old_name='segment_index',
            new_name='ind',
        ),
        migrations.RenameField(
            model_name='segment',
            old_name='segmenter',
            new_name='parent',
        ),
        migrations.AlterUniqueTogether(
            name='segment',
            unique_together={('ind', 'parent')},
        ),
    ]
