# Generated by Django 2.0.1 on 2018-03-23 19:38
# pylint: skip-file
import audiofield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='audio_file',
            field=audiofield.fields.AudioField(blank=True, help_text='Allowed type: .wav', upload_to=''),
        ),
    ]
