# Generated by Django 2.0.1 on 2018-02-19 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0002_auto_20180219_2236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='segment',
            old_name='end_position_in_song',
            new_name='end_position_in_samples',
        ),
        migrations.RenameField(
            model_name='segment',
            old_name='start_position_in_song',
            new_name='start_position_in_samples',
        ),
    ]
