# Generated by Django 2.0.1 on 2018-02-21 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0003_auto_20180219_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentlist',
            name='segmentation_status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('pending', 'Pending...'), ('done', 'Done')], default='not_started', max_length=15),
        ),
    ]
