# Generated by Django 2.0.1 on 2018-02-22 17:21

from django.db import migrations, models
import segmentation.models.segment_list


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0004_segmentlist_segmentation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentlist',
            name='segment_limits_IS',
            field=models.FileField(default='ss', upload_to=segmentation.models.segment_list.get_upload_path),
            preserve_default=False,
        ),
    ]
