# Generated by Django 2.0.1 on 2018-02-22 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0005_segmentlist_segment_limits_is'),
    ]

    operations = [
        migrations.RenameField(
            model_name='segmentlist',
            old_name='segment_limits_IS',
            new_name='data',
        ),
    ]
