# Generated by Django 2.0.1 on 2018-02-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0006_auto_20180222_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='segmentlist',
            name='data',
        ),
        migrations.AddField(
            model_name='segmentlist',
            name='data_path',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
