# Generated by Django 2.0.1 on 2018-02-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segmentation', '0008_auto_20180225_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='segment',
            old_name='index',
            new_name='segment_index',
        ),
        migrations.AlterField(
            model_name='segment',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterUniqueTogether(
            name='segment',
            unique_together={('segment_index', 'segment_list')},
        ),
    ]
