# Generated by Django 2.0.1 on 2018-02-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0009_song_sample_rate'),
        ('segmentation', '0009_auto_20180225_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='segmentlist',
            name='n_tempo_lags_per_segment',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AlterUniqueTogether(
            name='segmentlist',
            unique_together={('song', 'method', 'n_tempo_lags_per_segment')},
        ),
    ]
