# Generated by Django 2.0.1 on 2018-04-02 11:21
# pylint: skip-file
import audiofield.fields
from django.db import migrations, models
import song.models.song
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('processing_status', models.CharField(choices=[('not_started', 'Not started'), ('pending', 'Pending...'), ('failed', 'Failed'), ('done', 'Done')], default='not_started', max_length=15)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('tempo', models.FloatField(blank=True, null=True)),
                ('sample_rate', models.PositiveIntegerField(blank=True, default=44100)),
                ('original_file', audiofield.fields.AudioField(blank=True, help_text='Allowed type: .wav', max_length=500, upload_to=song.models.song.get_upload_path)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
