# Generated by Django 2.0.1 on 2018-01-07 15:03
# pylint: skip-file

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SongFiles',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('original_file', models.FileField(upload_to='original_songs/')),
            ],
            options={
                'verbose_name_plural': 'Song Files',
            },
        ),
        migrations.AddField(
            model_name='song',
            name='title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='song',
            name='files',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='song', to='song.SongFiles'),
        ),
    ]
