# Generated by Django 2.0.1 on 2018-03-04 21:27
# pylint: skip-file


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='data_path',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='tempo_estimation_status',
            field=models.CharField(choices=[('not_started', 'Not started'), ('pending', 'Pending...'), ('failed', 'Failed'), ('done', 'Done')], default='not_started', max_length=15),
        ),
    ]
