# Generated by Django 2.0.1 on 2018-02-15 19:44

import audiofield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_auto_20180107_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songfiles',
            name='original_file',
            field=audiofield.fields.AudioField(blank=True, help_text='Allowed type: .wav', upload_to='original_songs/'),
        ),
    ]
