# Generated by Django 2.0.1 on 2018-02-17 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_auto_20180215_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='files',
        ),
        migrations.AddField(
            model_name='songfiles',
            name='song',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='song.Song'),
        ),
    ]
