# Generated by Django 2.0.1 on 2018-02-22 17:21

import audiofield.fields
from django.db import migrations
import song.models.song_files


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0007_song_tempo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songfiles',
            name='original_file',
            field=audiofield.fields.AudioField(blank=True, help_text='Allowed type: .wav', upload_to=song.models.song_files.get_upload_path),
        ),
    ]
