# Generated by Django 2.0.1 on 2018-02-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0008_auto_20180222_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='sample_rate',
            field=models.PositiveIntegerField(blank=True, default=44100),
        ),
    ]
